# 공통 상수 정의

SHIFT_ORDER = ["D", "S", "N"]

DEFAULT_WEIGHTS = {
    "OFF_REQUEST_VIOLATION": 100,
    "CONSECUTIVE_WORK_PER_DAY": 20,
    "NIGHT_EXCESS_PER_SHIFT": 10,
    "UNFILLED_SLOT": 100,
}
